### ISSUE TITLE
How can I get a result like Figure 3 in your article?

### ISSUE THREAD

**Issue by songzwgithub** [kleok/INSAR4SM#2]
Hello,

When I run INSAR4SM completely, I get a shp file, but it stores data in the form of points. How should I convert it to the result like Figure 3 in your paper？

Kind regards,
Zhiwei Song

**Comment by kleok** [comment]
Dear Zhiwei Song,
First of all, thanks for your interest! I suggest to try to convert the point vector results to raster format. Some ways to do this convertion can be with python gdal functionaltities [here](https://gdal.org/programs/gdal_rasterize.html) or using QGIS [Rasterize (overwrite with attribute)](https://docs.qgis.org/3.28/en/docs/user_manual/processing_algs/gdal/vectorconversion.html). I will try to include this functionality in the next days. I hope my response will help you overcome this issue.

**Comment by songzwgithub** [comment]
Dear Dr. Karamvasis:
Thanks for your reply. I have learned a lot from your code and your article. Looking forward to your update!
