### ISSUE TITLE
ERA5-land file and sand_soilgrids, clay_soilgrids 

### ISSUE THREAD

**Issue by asteriospapas** [kleok/INSAR4SM#3]
Dear kleok, 

I was trying to test your software and I stumbled into a few problems.

I was trying to understand what products are required to download for the ERA5-land product. Here are a few questions.

- There are 2 products, hourly data and monthly averaged data. Which one should I select?
- Also which variables should I attach to download? 
- My dataset consists of data from 2020-2023, the hourly data only allows me to download one year-one month data. Is there another way to download the data all together, if that's the data that is needed. Also what time should I put, should I put all of them?
- If the product is the monthly averaged, which variables and parameters should I select?

- I know that there is a limitation to how much data can be downloaded, is there another way to merge the data if needed?

- In regards to the sand_soilgrids and clay_soilgrids downloaded from https://soilgrids.org/ what depth do I need to download?

Thank you in advance. 

I hope you can assist me in your software.

A.P.

**Comment by ofionnad** [comment]
I am just another user of this code, and also have some issues, but I have some suggestions for your questions above, which I have figured out through trial and error. It might help you somewhat. 

I selected the hourly ERA5 data. Downloaded each month at a time, for all dates in the month, with a single time specified. I downloaded the skin temperature and total precipitation parameters (I found that adding in other parameters caused some errors in the code). I concatenated these zipped netcdf files using nco (conda install -c conda-forge nco) and ncrcat. This output file is what I used as an input for meteorological file in INSAR4SM_app.py. 
I had to remove some dimensions from some of the data, for different months it appeared slightly different data shapes which confused ncrcat. Basically some of the months had a 'expver' dimensions, and others did not. 

For the soil and sand % grids, I used the 0-5cm depth. 

Hope that helps.

**Comment by kleok** [comment]
Hey @asteriospapas and @ofionnad,
Thanks for using InSAR4SM :smile:  I hope it will be useful for your work!
I will try to address your questions, in the following bullets.
- I agree with @ofionnad and I also suggest the use of  hourly ERA5-Land.
- The required variables to run InSAR4SM are Total precipitation and  Skin temperature. You can also download Volumetric soil water layer 1 separately (in a different  query) to assess the InSAR4SM SSM estimations with ERA5-Land SSM observations.
- I suggest you to pick a single ERA5-land time that is closest to the time of SAR acquisitions. In  case of a multi orbit scenario, please pick the times of all used orbits.
- According to my understanding there are two ways to download hourly ERA5-land data. The first way is by using the [GUI](https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-land?tab=form). You can download the data by using multiple time spans (e.g. first 2020-2022, then full months of 2023 and then days of last month of 2023). 
- A second way to download hourly ERA5-Land data is by using the cdsapi. You can have a look at this [functionality](https://github.com/kleok/FLOODPY/blob/5b9774e1a807c4ca68bcf7a6172d350c02ff6b11/floodpy/Download/Download_ERA5_precipitation.py#L64) which I have developed for another open source project. I hope this helps. 

- After the downloading of the ERA5-land data you will have multiple files and you can either merge the datasets (as @ofionnad suggested) or modify the following functionality
https://github.com/kleok/INSAR4SM/blob/f72fe26dc570a4c565a940d918e7eb9a25bb2983/insar4sm/prep_meteo.py#L31
Feel free to submit a PR  regarding this issue.
- Regarding the depth of sand and clay information, I agree with @ofionnad about the use of 0-5cm depth.

I will try to find some time and  improve the ERA5-land functionalities in the near future.

Let me know if you need any further clarifications :blush:

**Comment by kleok** [comment]
Hello @ofionnad and @asteriospapas,
I found some time and I commited an ERA5-land functionality that downloads `total_precipitation`, `skin_temperature` and `volumetric_soil_water_layer_1` given the `start_date` and `end_date`. It also merges the downloaded several nc files into a single nc file.
Hopefully this will be helpful for you :smile:

**Comment by asteriospapas** [comment]
Hello @kleok,

Still running it to get primary results.

Thank you for finding the time to update and refactor your code. Just a few comments from me till now.
1. In meteo_funcs.py, line 29, df2 = (meteo_df['tp__m'].shift().rolling(window=days_back, min_periods=1).sum().reset_index()), 
the days_back are set automatically to 24, thus shouldn't the first date, in the downloading meteo files, be set at least 24 days behind, if not isn't it going to output Nan on the first date? 
2. I see the downloading of the .nc meteo files are done for all times in days. Wouldn't it be faster to be able to set the time and only download that time (ex. 14:00), every day , every month? in download_ERA5_land.py.

Thanks again.

**Comment by kleok** [comment]
Hey @asteriospapas,
Thank you for your comments.
1. Maybe one potential solution can be to download all the data for the 24 days before the datetime of the first SAR acquisition.
2. I agree with you that it would be more efficient to download only a certain time and not all of them. Feel free to contribute to that :smiley:  

Thanks a lot for your feedback :smile:
