### ISSUE TITLE
INSAR4SM_point.py and ISMN data

### ISSUE THREAD

**Issue by aihui1104** [kleok/INSAR4SM#6]
Dear kleok,

1.  Regarding ISMN data download, the csv data I downloaded did not have the 'Datetime' column, resulting in an error in the program:

- INSAR4SM_point.py", line 162, in <module>
IMSN_df.index = pd.to_datetime(IMSN_df['Datetime'])
KeyError: 'Datetime'

  How to download ISMN data correctly?

2. Whether the geometry data of SM_polygons.geojson in the SM file obtained by running INSAR4SM_app.py is extracted and stored in the IMSN_polygon variable?

Thank you for your kind consideration.Looking forward to your reply!
Best wish!
Aihui

**Comment by kleok** [comment]
Hello Aihui :smiley: 
1. You need to create a csv file with two columns ( Datetime, sm_plot) as you can see in lines 153-155. For downloading ISMN data please have a look at the official ISMN downloader/reader [here](https://github.com/TUW-GEO/ismn).

https://github.com/kleok/INSAR4SM/blob/9caa75d5681874eae9472dbbd2085f1bb875813c/INSAR4SM_point.py#L153-L155
2. I am not sure I got your point. You need to provide a geojson file (in EPSG: 4326) with the polygon that will be considered for SSM estimation.
https://github.com/kleok/INSAR4SM/blob/d8f91c0a6f7c2d4b4b8a82b4085cf611b8c90f4e/INSAR4SM_point.py#L76-L78
Let me know if you need any clarifications.
Best regards :blush:
